//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoItem
    {
        public int PedidoItemId { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public Nullable<int> Pedido_PedidoId { get; set; }
        public Nullable<int> Pedido_ClienteId { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
